# Generated by Django 6.1.1 on 2026-10-03 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('mobile', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number (e.g. 9876543210).', regex='^(?:\\+91|0)?[6-9]\\d{9}$')])),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='Gujarat', max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit Indian PIN code.', regex='^[1-9][0-9]{5}$')])),
                ('gst_number', models.CharField(blank=True, db_index=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character Indian GSTIN format (e.g. 24AAAAA0000A1Z5).', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Initial ledger balance (Decimal)', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'company_name'], name='suppliers_s_name_be3ed3_idx'), models.Index(fields=['city', 'state'], name='suppliers_s_city_3e1b8f_idx')],
            },
        ),
    ]
