# Generated by Django 6.1.1 on 2026-10-03 17:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='ભાગ્યલક્ષ્મી એન્ટરપ્રાઇઝ', max_length=200)),
                ('address', models.CharField(default='જ્યોતિ હોસ્પિટલની સામે નુતન રોડ', max_length=255)),
                ('city', models.CharField(default='વિસનગર', max_length=100)),
                ('state', models.CharField(default='ગુજરાત', max_length=100)),
                ('pincode', models.CharField(default='384315', max_length=10)),
                ('mobile', models.CharField(default='9825000000', max_length=20)),
                ('whatsapp', models.CharField(default='9825000000', max_length=20)),
                ('email', models.EmailField(default='info@bhagyalaxmi.com', max_length=254)),
                ('gst_number', models.CharField(default='24AAAAA0000A1Z5', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_logo/')),
                ('invoice_prefix', models.CharField(default='SAL-', max_length=10)),
                ('order_prefix', models.CharField(default='ORD-', max_length=10)),
                ('currency', models.CharField(default='₹', max_length=10)),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Settings',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
    ]
