# Generated by Django 6.1.1 on 2026-10-03 17:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(db_index=True, max_length=150)),
                ('mobile', models.CharField(db_index=True, max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(default='Gujarat', max_length=100)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('order_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONFIRMED', 'Confirmed'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], db_index=True, default='NEW', max_length=20)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('COD', 'Cash On Delivery (COD)'), ('PENDING', 'Pending')], db_index=True, default='PENDING', max_length=20)),
                ('order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('courier_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('dispatch_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes only - strictly excluded from shipping label', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_online_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_orders', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='online_orders.onlineorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_order_items', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['order_id', 'created_at'], name='online_orde_order_i_ca2629_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['status', 'created_at'], name='online_orde_status_1b1f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['mobile', 'pincode'], name='online_orde_mobile_c76ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['tracking_number'], name='online_orde_trackin_f090d0_idx'),
        ),
    ]
