# Generated by Django 6.1.1 on 2026-10-03 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('STOCK_CHANGE', 'Stock Change'), ('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('RETURN', 'Return'), ('EXPENSE', 'Expense'), ('ORDER_STATUS_CHANGE', 'Order Status Change'), ('SETTINGS_CHANGE', 'Settings Change'), ('USER_CHANGE', 'User Change')], db_index=True, max_length=50)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_log_a_action_a31d18_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_log_a_model_n_8e90fb_idx')],
            },
        ),
    ]
