# Generated by Django 6.1.1 on 2026-10-03 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('gujarati_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, help_text='ADMIN ONLY - Private purchase cost', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('mrp', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='GST percentage (e.g., 0, 5, 12, 18, 28)', max_digits=5)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces (PCS)'), ('BOX', 'Box (BOX)'), ('PACK', 'Pack (PACK)'), ('KG', 'Kilogram (KG)'), ('GRAM', 'Gram (GRAM)'), ('LITRE', 'Litre (LITRE)'), ('METER', 'Meter (METER)'), ('PAIR', 'Pair (PAIR)'), ('SET', 'Set (SET)'), ('OTHER', 'Other')], default='PCS', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
